/*
    This file has been autogenerated using [generate_version_info.py].
    This file may be overwritten.
*/
#include "version.hpp"

namespace Project {

    const char* const Version::FRAMEWORK_VERSION = "v3.6.2";
    const char* const Version::PROJECT_VERSION = "909e562";
    const FwIndexType Version::LIBRARY_VERSIONS_COUNT = 0; 
    const char* const Version::LIBRARY_VERSIONS[] = { 
        nullptr
    };
}  // namespace Project
