version: '3.8'  # Specify the version

services:  
  yamcs_link_demo:
    build:
      context: ./yamcs_link_demo
    volumes:
      - mdb_shared:/mdb_shared 
    network_mode: "host" #Easier for a test

  yamcs_server:
    build:
      context: ./yamcs_server
    volumes:
      - mdb_shared:/mdb_shared  
    network_mode: "host"

volumes: 
  mdb_shared:  #This volume is shared between both containers and contains the yamcs mission databases that yamcs_link generates
